# podman-compose.yml
version: '3.3'

services:
  postgres:
    image: postgres:alpine
    env_file:
        - ./.postgres.env
    ports:
      - '5432:5432'
    volumes:
      - ./podman_volumes/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
        - ./.pgadmin.env
    ports:
      - '3080:3080'
